@extends('layouts.dashboard')
@section('heading','My Profile')
@section('content')
<div class="row g-4">
<div class="col-xl-8"><div class="card bg-white p-4"><h5>Account information</h5><form method="POST" action="{{ route('dashboard.profile.update') }}">@csrf<div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label">Full name</label><input name="name" class="form-control" value="{{ old('name',$u->name) }}" required></div><div class="col-md-6"><label class="form-label">Phone</label><input name="phone" class="form-control" value="{{ old('phone',$u->phone) }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input name="email" class="form-control" value="{{ old('email',$u->email) }}" required></div>
@if($u->isHelper())<div class="col-md-6"><label class="form-label">Experience (years)</label><input type="number" name="experience_years" class="form-control" value="{{ $u->helperProfile?->experience_years }}"></div><div class="col-12"><label class="form-label">Bio</label><textarea name="bio" class="form-control" rows="3">{{ $u->helperProfile?->bio }}</textarea></div><div class="col-md-6"><label class="form-label">Languages</label><input name="languages" class="form-control" value="{{ $u->helperProfile?->languages }}"></div><div class="col-md-6"><label class="form-label">Expected salary</label><input type="number" name="expected_salary" class="form-control" value="{{ $u->helperProfile?->expected_salary }}"></div><div class="col-md-6"><label class="form-label">Work type</label><select name="work_type" class="form-select"><option value="part_time" @selected($u->helperProfile?->work_type==='part_time')>Part-time</option><option value="full_time" @selected($u->helperProfile?->work_type==='full_time')>Full-time</option></select></div><div class="col-md-6"><label class="form-label">Working hours</label><input name="preferred_working_hours" class="form-control" value="{{ $u->helperProfile?->preferred_working_hours }}"></div><div class="col-md-8"><label class="form-label">Address</label><input name="address_line" class="form-control" value="{{ $u->helperProfile?->address_line }}"></div><div class="col-md-4"><label class="form-label">Pincode</label><input name="pincode" class="form-control" value="{{ $u->helperProfile?->pincode }}"></div>
@else<div class="col-md-8"><label class="form-label">Address</label><input name="address_line" class="form-control" value="{{ $u->customerProfile?->address_line }}"></div><div class="col-md-4"><label class="form-label">Pincode</label><input name="pincode" class="form-control" value="{{ $u->customerProfile?->pincode }}"></div>@endif
<div class="col-md-6"><label class="form-label">New password</label><input type="password" name="password" class="form-control" placeholder="Leave blank to keep current"></div><div class="col-md-6"><label class="form-label">Confirm password</label><input type="password" name="password_confirmation" class="form-control"></div></div><button class="btn btn-primary mt-4">Save changes</button></form></div></div>
<div class="col-xl-4"><div class="card bg-white p-4"><h5>Profile photo</h5>@if($u->helperProfile?->profile_photo)<img class="rounded-circle mb-3" style="width:110px;height:110px;object-fit:cover" src="{{ asset('storage/'.$u->helperProfile->profile_photo) }}">@else<div class="rounded-circle bg-brand text-white d-flex align-items-center justify-content-center mb-3" style="width:110px;height:110px;font-size:2rem">{{ mb_substr($u->name,0,1) }}</div>@endif @if($u->isHelper())<form method="POST" action="{{ route('dashboard.profile.photo') }}" enctype="multipart/form-data">@csrf<input type="file" name="photo" class="form-control" accept="image/*" required><button class="btn btn-outline-primary mt-2">Upload photo</button></form>@else<p class="small text-muted">Profile details can be updated from the form.</p>@endif<hr><span class="badge text-bg-light">{{ ucfirst($u->role) }} account</span></div></div></div>
@endsection
