<!DOCTYPE html>
<html lang="hi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>सहायिका खोजें — Sahayika</title>
    <meta name="description" content="Indore में घरेलू काम, खाना, Baby Care और Elder Care के लिए सहायिका खोजें।">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600;9..144,700&family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
    <style>
        :root{--ink:#16302E;--paper:#FBF5EA;--gold:#E8A33D;--gold2:#C97F1F;--maroon:#A63446;--teal:#2F6E68;--card:#FFFDF8;--line:rgba(22,48,46,.12)}
        *{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,sans-serif}a{text-decoration:none;color:inherit}.wrap{max-width:1180px;margin:auto;padding:0 24px}
        header{position:sticky;top:0;z-index:20;background:rgba(251,245,234,.94);backdrop-filter:blur(10px);border-bottom:1px solid var(--line)}
        nav{min-height:74px;display:flex;align-items:center;justify-content:space-between}.brand{font:700 1.45rem Fraunces,serif}.navlinks{display:flex;gap:28px;font-size:.92rem}.navlinks a{opacity:.75}.navlinks a:hover{opacity:1}.navbtn{padding:10px 18px;border-radius:99px;background:var(--ink);color:var(--paper);font-weight:600}
        .hero{padding:54px 0 34px;background:linear-gradient(180deg,#fffaf0 0%,var(--paper) 100%)}.eyebrow{display:inline-flex;gap:8px;align-items:center;color:var(--maroon);font:600 .72rem 'Space Grotesk';letter-spacing:.13em;text-transform:uppercase}.dot{width:7px;height:7px;border-radius:50%;background:var(--gold2)}h1{font:700 clamp(2rem,4vw,3.3rem) Fraunces,serif;line-height:1.08;margin:12px 0 10px}.hero p{color:rgba(22,48,46,.65);max-width:650px;line-height:1.6;margin:0}
        .searchbox{margin-top:28px;background:var(--card);border:1px solid var(--line);border-radius:22px;padding:8px;box-shadow:0 18px 45px -30px rgba(22,48,46,.35)}.searchgrid{display:grid;grid-template-columns:1.1fr 1fr auto;gap:8px}.field{padding:12px 16px;border-radius:15px;background:#fffaf1;border:1px solid transparent}.field:focus-within{border-color:rgba(232,163,61,.55)}label{display:block;font:600 .68rem 'Space Grotesk';text-transform:uppercase;letter-spacing:.1em;color:rgba(22,48,46,.55);margin-bottom:5px}.field select,.field input{width:100%;border:0;outline:0;background:transparent;font:600 .95rem Inter;color:var(--ink)}.btn{border:0;border-radius:15px;padding:0 25px;background:var(--gold);font:700 .93rem Inter;color:var(--ink);cursor:pointer}.btn:hover{background:var(--gold2)}
        .content{padding:34px 0 80px}.toolbar{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.count{font:700 1.25rem Fraunces,serif}.muted{font-size:.86rem;color:rgba(22,48,46,.58)}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.chip{padding:6px 10px;border-radius:99px;background:#fff4dc;border:1px solid rgba(232,163,61,.28);font-size:.78rem}
        .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:20px;transition:.2s;display:flex;flex-direction:column}.card:hover{transform:translateY(-3px);box-shadow:0 18px 35px -25px rgba(22,48,46,.45);border-color:rgba(47,110,104,.25)}.top{display:flex;gap:13px;align-items:center}.avatar{width:58px;height:58px;border-radius:18px;background:var(--teal);color:white;display:grid;place-items:center;font:700 1.2rem Fraunces,serif}.name{font:700 1.15rem Fraunces,serif;margin:0}.location{font-size:.78rem;color:rgba(22,48,46,.6);margin-top:3px}.status{margin-left:auto;padding:5px 9px;border-radius:99px;background:#e9f5ee;color:#276447;font-size:.68rem;font-weight:700}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:18px 0}.meta div{background:#fbf6eb;border-radius:12px;padding:10px}.meta small{display:block;color:rgba(22,48,46,.52);font-size:.68rem}.meta strong{font-size:.85rem}.services{display:flex;gap:6px;flex-wrap:wrap;min-height:49px}.service{padding:6px 9px;border-radius:99px;background:#f1f5f1;font-size:.73rem}.service.more{background:#fff1dc}.cardfoot{display:flex;justify-content:space-between;align-items:center;margin-top:18px;padding-top:15px;border-top:1px solid var(--line)}.salary{font-weight:700}.salary span{font-size:.68rem;font-weight:500;color:rgba(22,48,46,.55)}.view{color:var(--maroon);font-weight:700;font-size:.82rem}.empty{text-align:center;padding:70px 20px;background:var(--card);border:1px dashed var(--line);border-radius:22px}.empty h2{font:700 1.7rem Fraunces,serif;margin:0 0 8px}.empty p{color:rgba(22,48,46,.6)}.reset{display:inline-block;margin-top:8px;padding:10px 18px;border-radius:99px;background:var(--ink);color:white;font-weight:600}.pagination{margin-top:28px}.pagination nav{display:block}.pagination .flex{justify-content:center;gap:5px}.pagination a,.pagination span{border-radius:9px!important}
        @media(max-width:850px){.navlinks{display:none}.searchgrid{grid-template-columns:1fr}.btn{height:50px}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:580px){.wrap{padding:0 16px}.hero{padding-top:35px}.grid{grid-template-columns:1fr}.toolbar{align-items:start;gap:12px;flex-direction:column}.navbtn{display:none}}
    </style>
</head>
<body>
<header><div class="wrap"><nav><a href="{{ route('home') }}" class="brand">Sahayika</a><div class="navlinks"><a href="{{ route('home') }}">होम</a><a href="{{ route('helpers.index') }}">सहायिका खोजें</a><a href="{{ route('register') }}">सहायिका बनें</a></div><a class="navbtn" href="{{ route('login') }}">लॉगिन</a></nav></div></header>
<section class="hero"><div class="wrap"><span class="eyebrow"><i class="dot"></i> Indore · Madhya Pradesh</span><h1>आपके घर के लिए सही<br>सहायिका खोजें।</h1><p>काम, इलाके और आपकी जरूरत के हिसाब से profiles देखें। अनुभव, उपलब्धता और अनुमानित वेतन एक ही जगह पर compare करें।</p>
<form class="searchbox" method="GET" action="{{ route('helpers.index') }}"><div class="searchgrid"><div class="field"><label>किस काम के लिए</label><select name="service"><option value="">सभी सेवाएं</option>@foreach($services as $item)<option value="{{ $item->slug }}" @selected(request('service') === $item->slug)>{{ $item->name_hi ?: $item->name }}</option>@endforeach</select></div><div class="field"><label>अपना इलाका</label><input name="locality" value="{{ request('locality') }}" list="indore-localities" placeholder="जैसे Vijay Nagar या Nipania"><datalist id="indore-localities">@foreach($localities as $item)<option value="{{ $item->name }}">@endforeach</datalist></div><button class="btn" type="submit">सहायिका खोजें →</button></div></form>
</div></section>
<main class="content"><div class="wrap"><div class="toolbar"><div><div class="count">{{ $helpers->total() }} profiles मिले</div><div class="muted">हर profile में services, experience और availability देखें</div></div><div class="muted">Indore demo directory</div></div>
@if(request()->filled('service') || request()->filled('locality'))<div class="chips">@if($service)<span class="chip">काम: {{ $service->name_hi ?: $service->name }}</span>@endif @if($locality)<span class="chip">इलाका: {{ $locality->name }}</span>@elseif(request('locality'))<span class="chip">इलाका: {{ request('locality') }}</span>@endif</div><br>@endif
@if($helpers->count())<div class="grid">@foreach($helpers as $helper)<a class="card" href="{{ route('helpers.show',$helper) }}"><div class="top"><div class="avatar">{{ collect(preg_split('/\s+/', trim($helper->user->name)))->map(fn($part)=>mb_substr($part,0,1))->take(2)->implode('') }}</div><div><h2 class="name">{{ $helper->user->name }}</h2><div class="location">{{ $helper->locality?->name }}, {{ $helper->locality?->city?->name }}</div></div>@if($helper->immediate_availability)<span class="status">Available</span>@endif</div><div class="meta"><div><small>अनुभव</small><strong>{{ $helper->experience_years }} साल</strong></div><div><small>काम का प्रकार</small><strong>{{ $helper->work_type === 'full_time' ? 'Full-time' : 'Part-time' }}</strong></div></div><div class="services">@foreach($helper->services->take(3) as $item)<span class="service">{{ $item->name_hi ?: $item->name }}</span>@endforeach @if($helper->services->count()>3)<span class="service more">+{{ $helper->services->count()-3 }} और</span>@endif</div><div class="cardfoot"><div class="salary">₹{{ number_format($helper->expected_salary) }} <span>/ माह</span></div><span class="view">Profile देखें →</span></div></a>@endforeach</div><div class="pagination">{{ $helpers->links() }}</div>@else<div class="empty"><h2>इस search के लिए profile नहीं मिली</h2><p>इलाका या service बदलकर फिर से कोशिश करें।</p><a class="reset" href="{{ route('helpers.index') }}">सभी profiles देखें</a></div>@endif
</div></main>
</body></html>
